[versions]
agp = "9.3.1"
kotlin = "2.4.10"
ksp = "2.3.10"
gson = "2.14.0"
koin-bom = "4.2.2"
frogoAndroid = "3.0.5"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# --------------------------------------------------------------------------------------------------

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin-bom" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin-bom" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin-bom" }
koin-android-compat = { group = "io.insert-koin", name = "koin-android-compat", version.ref = "koin-bom" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin-bom" }

frogo-sdk = { group = "com.github.frogobox.frogo-sdk", name = "frogo-core-android", version.ref = "frogoAndroid" }
frogo-sdk-core = { group = "com.github.frogobox.frogo-sdk", name = "frogo-core", version.ref = "frogoAndroid" }
frogo-ui = { group = "com.github.frogobox.frogo-sdk", name = "frogo-ui-base", version.ref = "frogoAndroid" }
frogo-recyclerview = { group = "com.github.frogobox.frogo-sdk", name = "frogo-ui-recyclerview", version.ref = "frogoAndroid" }

# --------------------------------------------------------------------------------------------------

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jvm-library = { id = "java-library"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jvm-android = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
