[versions]
agp = "8.12.2"
androidMavenGradlePlugin = "2.1"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"

gson = "2.13.1"

koin-bom = "4.1.0"

frogoAndroid = "2.3.2"

[libraries]
android-maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "androidMavenGradlePlugin" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# --------------------------------------------------------------------------------------------------

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-bom" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin-bom" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin-bom" }

frogo-sdk = { group = "com.github.frogobox.frogo-sdk", name = "core-sdk-android", version.ref = "frogoAndroid" }
frogo-sdk-core = { group = "com.github.frogobox.frogo-sdk", name = "core-sdk", version.ref = "frogoAndroid" }

frogo-ui = { group = "com.github.frogobox.frogo-sdk", name = "core-ui-android", version.ref = "frogoAndroid" }

frogo-recyclerview = { group = "com.github.frogobox.frogo-sdk", name = "frogo-recycler-view", version.ref = "frogoAndroid" }

# --------------------------------------------------------------------------------------------------

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jvm-library = { id = "java-library"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jvm-android = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }