[versions]
agp = "9.4.0"
kotlin = "2.4.20"
ksp = "2.3.10"
gson = "2.14.0"
hilt = "2.60.1"
frogoAndroid = "3.0.10"
androidxActivity = "1.13.0"
androidxFragment = "1.9.0"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# --------------------------------------------------------------------------------------------------

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }

frogo-sdk = { group = "com.github.frogobox.frogo-sdk", name = "frogo-core-android", version.ref = "frogoAndroid" }
frogo-sdk-core = { group = "com.github.frogobox.frogo-sdk", name = "frogo-core", version.ref = "frogoAndroid" }
frogo-ui = { group = "com.github.frogobox.frogo-sdk", name = "frogo-ui-base", version.ref = "frogoAndroid" }
frogo-recyclerview = { group = "com.github.frogobox.frogo-sdk", name = "frogo-ui-recyclerview", version.ref = "frogoAndroid" }

# --------------------------------------------------------------------------------------------------

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jvm-library = { id = "java-library"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jvm-android = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
